[package]
name = "oqci"
description = "The Open Quantum Compiler Infrastructure"
version = "0.1.0"
readme = "README.md"
edition = "2024"

license = "Apache-2.0"
repository = "https://github.com/AndyFerns/oqci"

[lib]
name = "oqci"
path = "src/lib.rs"

[[bin]]
name = "oqci"
path = "src/main.rs"

[dependencies]
thiserror = "2"
petgraph = "0.6"
