//! QCO-IR → QIR lowering.
//!
//! Emits **textual, LLVM-compatible QIR** (Quantum Intermediate Representation)
//! following the classic typed-pointer form used by the QIR specification:
//! opaque `%Qubit` / `%Result` types, `__quantum__qis__*` quantum intrinsics,
//! `__quantum__rt__*` runtime calls, and a single `entry_point` function
//! carrying Base-Profile module flags.
//!
//! # Scope & profile
//!
//! Phase 0 has no backend; QIR emission is the boundary. We emit a module
//! targeting the **QIR Base Profile** shape (static qubit/result ids via
//! `inttoptr`, no classical control flow). Operations are emitted in the
//! deterministic topological order given by
//! [`crate::ir::qco::QcoCircuit::topological_ops`].
//!
//! Two honesty caveats, both documented in `docs/qir_lowering.md`:
//!
//! - **Extended intrinsics.** Gates outside the QIR standard instruction set
//!   (`p`, `u`, `cy`, `swap`, `ccx`, `id`, and any [`crate::ir::GateKind::Opaque`])
//!   are emitted as declared `__quantum__qis__*` externs. They parse as valid
//!   LLVM IR; a future decomposition pass (Phase 3) can lower them to the
//!   standard set.
//! - **Mid-circuit measurement.** Circuits with a measurement before later gates
//!   are emitted in program order. Strict Base-Profile conformance
//!   (measurements last) would need a deferred-measurement pass, also Phase 3.
//!
//! # Float encoding
//!
//! Angle parameters are emitted as LLVM hexadecimal `double` literals
//! (`0x` + the 16 IEEE-754 bits), which LLVM always accepts exactly — avoiding
//! any lossy decimal-formatting pitfalls.

use std::collections::BTreeMap;

use crate::ir::error::IrError;
use crate::ir::qc::Instruction;
use crate::ir::qco::QcoCircuit;
use crate::ir::types::{ClbitId, GateKind, QubitId};

/// Lowers a QCO-IR circuit to a QIR module as textual LLVM IR.
///
/// # Errors
///
/// Propagates [`IrError::CyclicGraph`] from the topological traversal (which
/// cannot occur for a graph built from valid QC-IR).
pub fn emit_qir(dag: &QcoCircuit) -> Result<String, IrError> {
    let ops = dag.topological_ops()?;

    let mut declarations: BTreeMap<String, String> = BTreeMap::new();
    let mut body = String::new();
    let mut measured: Vec<ClbitId> = Vec::new();

    for (_, inst) in &ops {
        emit_instruction(inst, &mut body, &mut declarations, &mut measured);
    }

    // Record measured results (Base-Profile output recording), ascending.
    measured.sort_by_key(|c| c.index());
    measured.dedup();
    if !measured.is_empty() {
        declarations.insert(
            "__quantum__rt__result_record_output".to_string(),
            "declare void @__quantum__rt__result_record_output(%Result*, i8*)".to_string(),
        );
        for c in &measured {
            body.push_str(&format!(
                "  call void @__quantum__rt__result_record_output({}, i8* null)\n",
                result_val(*c)
            ));
        }
    }

    let entry = sanitize_symbol(dag.name());
    let mut out = String::new();
    out.push_str(&format!("; QIR module for circuit `{}`\n", dag.name()));
    out.push_str("; Generated by OQCI (Phase 0) — QIR Base Profile, textual form.\n");
    out.push_str(&format!("source_filename = \"{}\"\n\n", dag.name()));
    out.push_str("%Qubit = type opaque\n");
    out.push_str("%Result = type opaque\n\n");

    for decl in declarations.values() {
        out.push_str(decl);
        out.push('\n');
    }
    out.push('\n');

    out.push_str(&format!("define void @{entry}() #0 {{\n"));
    out.push_str("entry:\n");
    out.push_str(&body);
    out.push_str("  ret void\n");
    out.push_str("}\n\n");

    out.push_str(&format!(
        "attributes #0 = {{ \"entry_point\" \"output_labeling_schema\" \
         \"qir_profiles\"=\"base_profile\" \
         \"required_num_qubits\"=\"{}\" \"required_num_results\"=\"{}\" }}\n",
        dag.num_qubits(),
        dag.num_clbits()
    ));

    Ok(out)
}

fn emit_instruction(
    inst: &Instruction,
    body: &mut String,
    declarations: &mut BTreeMap<String, String>,
    measured: &mut Vec<ClbitId>,
) {
    match inst {
        Instruction::Gate { kind, qubits } => {
            let fname = intrinsic_name(kind);
            // Argument list: parameters (doubles) first, then qubit operands.
            let mut arg_tys: Vec<String> = Vec::new();
            let mut arg_vals: Vec<String> = Vec::new();
            for p in kind.params() {
                arg_tys.push("double".to_string());
                arg_vals.push(format!("double {}", llvm_double(p.radians())));
            }
            for q in qubits {
                arg_tys.push("%Qubit*".to_string());
                arg_vals.push(qubit_val(*q));
            }
            register_decl(declarations, &fname, &arg_tys);
            body.push_str(&format!("  call void @{fname}({})\n", arg_vals.join(", ")));
        }
        Instruction::Measure { qubit, target } => {
            let fname = "__quantum__qis__mz__body".to_string();
            register_decl(
                declarations,
                &fname,
                &["%Qubit*".to_string(), "%Result*".to_string()],
            );
            body.push_str(&format!(
                "  call void @{fname}({}, {})\n",
                qubit_val(*qubit),
                result_val(*target)
            ));
            measured.push(*target);
        }
        Instruction::Reset { qubit } => {
            let fname = "__quantum__qis__reset__body".to_string();
            register_decl(declarations, &fname, &["%Qubit*".to_string()]);
            body.push_str(&format!("  call void @{fname}({})\n", qubit_val(*qubit)));
        }
    }
}

/// Returns the fully-qualified QIR intrinsic function name for a gate.
fn intrinsic_name(kind: &GateKind) -> String {
    match kind {
        // Standard QIR intrinsics with irregular names.
        GateKind::Cx => "__quantum__qis__cnot__body".to_string(),
        GateKind::Sdg => "__quantum__qis__s__adj".to_string(),
        GateKind::Tdg => "__quantum__qis__t__adj".to_string(),
        // Everything else uses `__quantum__qis__<mnemonic>__body`. For extended
        // gates (id, p, u, cy, swap, ccx, opaque) the runtime must supply the
        // intrinsic; see docs/qir_lowering.md.
        other => format!("__quantum__qis__{}__body", other.mnemonic()),
    }
}

fn register_decl(declarations: &mut BTreeMap<String, String>, fname: &str, arg_tys: &[String]) {
    declarations
        .entry(fname.to_string())
        .or_insert_with(|| format!("declare void @{fname}({})", arg_tys.join(", ")));
}

fn qubit_val(q: QubitId) -> String {
    format!("%Qubit* inttoptr (i64 {} to %Qubit*)", q.index())
}

fn result_val(c: ClbitId) -> String {
    format!("%Result* inttoptr (i64 {} to %Result*)", c.index())
}

/// Formats an `f64` as an LLVM hexadecimal `double` literal (exact).
fn llvm_double(x: f64) -> String {
    format!("0x{:016X}", x.to_bits())
}

/// Reduces a circuit name to a valid LLVM global identifier, defaulting to
/// `main` if nothing usable remains.
fn sanitize_symbol(name: &str) -> String {
    let s: String = name
        .chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() || c == '_' {
                c
            } else {
                '_'
            }
        })
        .collect();
    if s.is_empty() || s.chars().next().is_some_and(|c| c.is_ascii_digit()) {
        format!("main_{s}")
    } else {
        s
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ir::qc::CircuitBuilder;
    use crate::ir::qc_to_qco;

    fn qir_of(build: impl FnOnce(&mut CircuitBuilder)) -> String {
        let mut b = CircuitBuilder::new("test");
        build(&mut b);
        let circuit = b.build().unwrap();
        let dag = qc_to_qco(&circuit).unwrap();
        emit_qir(&dag).unwrap()
    }

    #[test]
    fn empty_circuit_emits_valid_skeleton() {
        let qir = qir_of(|_| {});
        assert!(qir.contains("%Qubit = type opaque"));
        assert!(qir.contains("define void @test() #0"));
        assert!(qir.contains("ret void"));
        assert!(qir.contains("\"entry_point\""));
    }

    #[test]
    fn bell_emits_h_and_cnot() {
        let qir = qir_of(|b| {
            let q0 = b.alloc_qubit();
            let q1 = b.alloc_qubit();
            b.h(q0).cx(q0, q1);
        });
        assert!(qir.contains("@__quantum__qis__h__body"));
        assert!(qir.contains("@__quantum__qis__cnot__body"));
        assert!(qir.contains("required_num_qubits\"=\"2\""));
    }

    #[test]
    fn measurement_emits_mz_and_record_output() {
        let qir = qir_of(|b| {
            let q0 = b.alloc_qubit();
            let c0 = b.alloc_clbit();
            b.h(q0).measure(q0, c0);
        });
        assert!(qir.contains("@__quantum__qis__mz__body"));
        assert!(qir.contains("@__quantum__rt__result_record_output"));
        assert!(qir.contains("required_num_results\"=\"1\""));
    }

    #[test]
    fn rotation_emits_hex_double() {
        let qir = qir_of(|b| {
            let q0 = b.alloc_qubit();
            b.rz(std::f64::consts::PI.into(), q0);
        });
        // PI encoded as its exact IEEE-754 hex.
        assert!(qir.contains(&format!("double 0x{:016X}", std::f64::consts::PI.to_bits())));
        assert!(qir.contains("@__quantum__qis__rz__body"));
    }

    #[test]
    fn declarations_are_deduplicated() {
        let qir = qir_of(|b| {
            let q0 = b.alloc_qubit();
            b.x(q0).x(q0).x(q0);
        });
        assert_eq!(
            qir.matches("declare void @__quantum__qis__x__body").count(),
            1
        );
    }

    #[test]
    fn reset_emits_reset_intrinsic() {
        let qir = qir_of(|b| {
            let q0 = b.alloc_qubit();
            b.reset(q0);
        });
        assert!(qir.contains("@__quantum__qis__reset__body"));
    }
}
